### PR TITLE
Update lua/python binding according to new matrix table get interface.

### PR DESCRIPTION
**Pull request by huxuan**
- Use new matrix get interface in `c_api`.
- [lua/python binding] Update lua/python binding according to `c_api` change.
- [lua/python binding] Add unittest for new matrix table get interface.
- [lua binding] Better conversion between `ffi.cdata` and `torch.Tensor`.
- Minor changes.

P.S. Based on #62

### CODE REVIEW

**Comment by you-n-g** [comment]
I've reviewed it. It's OK
But It is labeled `work-in-progress` . Can I merge it?

**Comment by huxuan** [comment]
@you-n-g The codebase is workable based on the merge of #62 . After that PR being merged, I will merge changes there and change the label to `ready-for-review`.

**Comment by huxuan** [comment]
Hi @you-n-g , the PR has been updated with the merge of upstream.

And the `size` issue has also been resolved.

**Comment by you-n-g** [comment]
Cool! merged

**Pull request merged**
