### PR TITLE
simple example of python api

### PR DESCRIPTION
**Pull request by you-n-g**
* add the mpi dependancy into cmakelist for multiverso.so
* simple demo of python api

### CODE REVIEW

**Comment by huxuan** [comment]
Would you please help me to confirm how to run the test?

I tried to run `python test.py` under the exact directory but encounter some `OSError` in `libmultiverso.so`

**Comment by huxuan** [comment]
And actually I have a little concern about the folder structure. Maybe we should have a `binding` folder under root path in case we will both have python and lua binding? Otherwise, whenever we decide to support one more programming language, there will be another extra folder at the root level. I do not think that is a good idea.

**Comment by you-n-g** [comment]
If you want you run the test,  you should 
1) follow the [readme](https://github.com/Microsoft/multiverso#build) to compile the project.
I changed the cmakelists.txt,  you should recompile it.
2) `cd python/multiverso` and  run `python test.py` to run the python test.

I only test it in linux so far.


I agree with you on changing the folder structure.

**Comment by feiga** [comment]
I think both folder structure is OK

**Comment by chivee** [comment]
hi @you-n-g , in case for the future development, Let's create the `folder` binding under the `root`.

**Comment by you-n-g** [comment]
OK, I'll create the folder.

**Pull request merged**
